application: geholimport
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots.txt
  static_files: robots.txt

- url: /.*
  script: main.py

